project:
  type: website
  
website:
  title: "Yichen's website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd
      - href: blog.qmd
        text: Projects
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

